version: '1.0'

services:
    develop:
        image: deli/micromouse
        command: /bin/bash

        stdin_open: true
        tty: true

        environment:
            - "DISPLAY"
            - "QT_X11_NO_MITSHM=1"
        volumes:
            - /home/deli/Documents/husarion/ros-micromouse/ws:/root/ws

        network_mode: host

    micromouse_bringup:
        image: deli/micromouse
        privileged: true
        network_mode: host
        ipc: host
        environment:
            - "DISPLAY"
            - "QT_X11_NO_MITSHM=1"
        command: bash -c "cd /root/ws && colcon build --executor parallel && source /root/ws/install/setup.bash && ros2 launch micromouse_bringup micromouse_bringup.launch.py"
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - /dev/dri:/dev/dri
            - /home/deli/Documents/husarion/ros-micromouse/ws:/root/ws

    micromouse_controller:
        image: deli/micromouse
        privileged: true
        ipc: host
        network_mode: host
        environment:
            - "DISPLAY"
            - "QT_X11_NO_MITSHM=1"
        command: bash -c "cd /root/ws && colcon build --executor parallel && source /root/ws/install/setup.bash && ros2 launch micromouse_robot micromouse_robot.launch.py"
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - /dev/dri:/dev/dri
            - /home/deli/Documents/husarion/ros-micromouse/ws:/root/ws

    rviz:
        image: deli/micromouse
        command: bash -c "source /root/ws/install/setup.bash && rviz2 -d /root/ws/src/micromouse_description/rviz/micromouse_rviz.rviz"
        volumes:
            - /home/deli/Documents/husarion/ros-micromouse/ws:/root/ws
            - /tmp/.X11-unix:/tmp/.X11-unix
            - /dev/dri:/dev/dri
        network_mode: host
        environment:
            - "DISPLAY"
            - "QT_X11_NO_MITSHM=1"


