version: '1.0'

services:
    micromouse_bringup:
        build: .
        environment:
            - DISPLAY
            - QT_X11_NO_MITSHM = 1
        command: ros2 launch micromouse_bringup micromouse_bringup.launch.py
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            - /dev/dri:/dev/dri

    micromouse_controller:
        build: .
        command: ros2 launch micromouse_robot micromouse_robot.launch.py